name: Update data

on:
  # Run every month on the 2nd at 12:00 UTC
  schedule:
    - cron: "0 12 2 * *"
  push:
    paths:
      - ".github/workflows/update-data.yml"
      - "config.php"
      - "overpass/*"
  pull_request:
    paths:
      - ".github/workflows/update-data.yml"
      - "config.php"
      - "overpass/*"

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: EqualStreetNames/equalstreetnames
          persist-credentials: false
          submodules: true
      - name: Use PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: curl, pdo, sqlite3
      - name: Validate composer.json and composer.lock
        working-directory: process
        run: composer validate
      - name: Install dependencies
        working-directory: process
        run: composer install --prefer-dist --no-progress

      - name: Checkout submodule to master
        working-directory: cities/germany/berlin
        run: git checkout -q master
      - name: Update sub-modules
        run: git submodule update --remote --merge cities/germany/berlin

      - name: Run update
        working-directory: process
        run: composer run update-data -- --city=germany/berlin

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Berlin
      #     path: cities/germany/berlin/data/*

      - name: Commit sub-module
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: cities/germany/berlin
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add data/*
          git commit -m "🗃 Update data"
      - name: Push to sub-module
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name != 'pull_request' }}
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          directory: cities/germany/berlin
          repository: EqualStreetNames/equalstreetnames-berlin

      - name: Commit repository
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull
          git add cities/germany/berlin
          git commit -m "🗃 Update Berlin sub-module"
      - name: Push to repository
        uses: ad-m/github-push-action@master
        if: ${{ github.event_name != 'pull_request' }}
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          repository: EqualStreetNames/equalstreetnames
